/*
 * This file was generated by the Gradle 'init' task.
 */

val sqldelightVersion = "2.0.1"

plugins {
//    val sqldelightVersion = sql
    id("learninggradle.kotlin-library-conventions")
    id("io.ktor.plugin") version "2.3.6"
    id("app.cash.sqldelight") version "2.0.1"
}

dependencies {
    implementation("io.ktor:ktor-server-websockets")
    implementation("io.ktor:ktor-server-core")
    implementation("io.ktor:ktor-server-netty")
    implementation("app.cash.sqldelight:jdbc-driver:$sqldelightVersion")
    implementation("com.zaxxer:HikariCP:5.1.0")
}

application {
//    mainClass.set("com.example.ApplicationKt")   // when Ktor embeddedServer is used
    mainClass.set("io.ktor.server.netty.EngineMain")
}

sqldelight {
    databases {
        create("Database") {
            packageName.set("com.example")
            dialect("app.cash.sqldelight:mysql-dialect:$sqldelightVersion")
        }
    }
}
