/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("learninggradle.kotlin-library-conventions")
    id("io.ktor.plugin") version "2.3.6"
}

dependencies {
    implementation("io.ktor:ktor-server-websockets")
//    implementation("io.ktor:ktor-server-core")
//    implementation("io.ktor:ktor-server-netty")
}

application {
//    mainClass.set("com.example.ApplicationKt")   // when Ktor embeddedServer is used
    mainClass.set("io.ktor.server.netty.EngineMain")
}