package example.com
/*
 * This Kotlin source file was generated by the Gradle "init" task.
 */
//package learninggradle.list

import org.junit.jupiter.api.Test

import org.junit.jupiter.api.Assertions.*

class ClientTest {
    @Test fun testConstructor() {
        val list = listOf(1)
        assertEquals(1, list.size)
    }

}
