/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("learninggradle.kotlin-application-conventions")
}

dependencies {
    implementation("org.apache.commons:commons-text")
    implementation(project(":ws-chat-client"))
}

application {
    // Define the main class for the application.
    mainClass.set("learninggradle.app.AppKt")
}
