/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package learninggradle.app

//import learninggradle.utilities.StringUtils

//import org.apache.commons.text.WordUtils

fun main() {
    val text = "holA"    // StringUtils.split(MessageUtils.getMessage())
//    val result = StringUtils.join(tokens)
    println(text.uppercase())
}
