/*
 * This file was generated by the Gradle 'init' task.
 */

val ktorVersion = "2.3.6"

plugins {
    id("learninggradle.kotlin-library-conventions")
    // Support convention plugins written in Kotlin. Convention plugins are build scripts in 'src/main' that automatically become available as plugins in the main build.
    `kotlin-dsl`
}
dependencies {
    implementation(libs.kotlin.gradle.plugin)
    implementation("io.ktor:ktor-client-core:$ktorVersion")
    implementation("io.ktor:ktor-client-cio:$ktorVersion")
    api(project(":ws-chat-server"))
}
